### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.report'

### ISSUE THREAD

**Issue by chup4cabra** [abrignoni/ALEAPP#119]
Hi,
after cloning "Aleapp" from github and installing the requirements packages, when I execute this command:

$ python3.9 aleapp.py -h

I get this error:

Traceback (most recent call last):
  File "/opt/ALEAPP/aleapp.py", line 3, in <module>
    import scripts.report as report
ModuleNotFoundError: No module named 'scripts.report'

How can I solve this issue?

Thank you.

**Comment by abrignoni** [comment]
Make sure the scripts folder is there and that it did not got lost or corrupted during the zip decompression process.
I tried it and it worked as expected.

<img width="559" alt="Screen Shot 2021-03-04 at 11 31 05 AM" src="https://user-images.githubusercontent.com/28718987/109996631-6770e280-7cdd-11eb-8406-34cf489ea009.png">

**Comment by ydkhatri** [comment]
Closing for lack of response..
