### ISSUE TITLE
Recent Activity report missing Snapshot_image pictures

### ISSUE THREAD

**Issue by abrignoni** [abrignoni/ALEAPP#12]
<img width="832" alt="Screen Shot 2020-03-10 at 11 15 21 AM" src="https://user-images.githubusercontent.com/28718987/76327496-75557880-62c0-11ea-91ff-9fcb4b03878c.png">

**Comment by ydkhatri** [comment]
Not seeing this, tested zip and fs. Seems fine here.

**Comment by abrignoni** [comment]
I'm running from macOS Catalina. You?

**Comment by ydkhatri** [comment]
Windows

**Comment by abrignoni** [comment]
Yes. Confirmed it works on Windows.
Will give the code a look. The images are placed in the correct directory and everything. The base path is just not showing up.

**Comment by ydkhatri** [comment]
This pull should fix it.
