### ISSUE TITLE
Sorting subcategories alphabetically

### ISSUE THREAD

**Issue by abrignoni** [abrignoni/ALEAPP#126]
Any thoughts on sorting subcategories alphabetically @ydkhatri ?
See Chromiun category. Alphabetical subcategories would make it look cleaner I think.

<img width="274" alt="Screen Shot 2021-03-19 at 8 48 54 AM" src="https://user-images.githubusercontent.com/28718987/111782889-f2320f80-888f-11eb-8a9d-f1fc9be5563a.png">

**Comment by ydkhatri** [comment]
Hmm, yes it would look a lot cleaner. I believe currently the order is same as how it reads the files on disk (the walk() function) [here](https://github.com/abrignoni/ALEAPP/blob/2b592ba2f68121014629f6a61e17eb8313b79304/scripts/report.py#L129). 

https://github.com/abrignoni/ALEAPP/blob/2b592ba2f68121014629f6a61e17eb8313b79304/scripts/report.py#L129

I'm looking at some old outputs from earlier and they are all sorted for me. Which particular image are you using ?

**Comment by abrignoni** [comment]
I'm using Josh's Android 11 tar.

**Comment by abrignoni** [comment]
Image here:
https://thebinaryhick.blog/2020/10/07/new-android-image-available-this-one-goes-to-11/

**Comment by abrignoni** [comment]
If I sort the files list before line 129 it sorts as I would like it. If you agree I will send the PR.

<img width="290" alt="Screen Shot 2021-03-19 at 12 16 26 PM" src="https://user-images.githubusercontent.com/28718987/111810950-f02a7980-88ac-11eb-8d66-3117d015f846.png">

**Comment by abrignoni** [comment]
Sorted list PR merged.
