### ISSUE TITLE
Missing requirements

### ISSUE THREAD

**Issue by kibaffo33** [abrignoni/ALEAPP#178]
Hey Briggs. Big fan of the XLEAPP tools, thanks for all your efforts and sharing.

Requirements need updating following SGallery Calculator Vaults addition (https://github.com/abrignoni/ALEAPP/commit/4e44c18ec1fdad0ce0265444dc2b097ba1f86ea5). Standby for PR...

**Comment by kibaffo33** [comment]
PR https://github.com/abrignoni/ALEAPP/pull/179 relates

**Comment by abrignoni** [comment]
What platform are you seeing the error in? Is mimetypes-magic==0.4.30 necessary? I don't remember having to pip install it nor would I know where would it be used. Current code identifies the mimetypes using the magic or filetype libraries. Maybe adding mimetypes-magic==0.4.30 causes some sort of conflict? Not sure what might be going on. Thoughts?

**Comment by kibaffo33** [comment]
Ah, I probably misunderstood which `magic` library you're using. Is it `python-magic-bin`? 

I was on a MacOS 12 (Intel) earlier, but also had the same issue with Windows 10. 
Now I'm on a Mac with M1, which `python-magic-bin` doesn't support.

May have to come back to this on Monday...

**Comment by kibaffo33** [comment]
You were right, `mimetypes-magic` was unnecessary!

I've removed it from https://github.com/abrignoni/ALEAPP/pull/179 and this works now...

**Comment by kibaffo33** [comment]
Thanks for merging!
https://github.com/abrignoni/ALEAPP/commit/d7d3bfbe9f06ae52702e1561b99de570edecf7f4
