### ISSUE TITLE
Pending artifacts

### ISSUE THREAD

**Issue by abrignoni** [abrignoni/ALEAPP#21]
List of items I am working on or plan to work on in the near future:
- [x] Chrome browser history
- [x] Chrome browser downloads
- [x] Chrome browser keyword search terms
- [x] Chrome browser top sites
- [x] Chrome browser login data
- [x] Chrome browser bookmarks
- [x] Chrome browser cookies
- [ ] Chrome Current Tabs
- [ ] Android Launcher - Icon positions on screens. (Script already made. Need to merge)
- [x] SIM info
- [x] IMSI info
- [x] Downloads
- [x] Google Play Installed Applications
- [x] Google Play Searches
- [x] Google Now & Quick Search Box
- [x] Wi-Fi profiles

**Comment by ydkhatri** [comment]
Added Google Now & Quick Search Box. This is an interesting artifact I've been looking at.

**Comment by abrignoni** [comment]
Nice!!! Really interested in the Google Now data. Good one.
