### ISSUE TITLE
python-magic-bin requirement

### ISSUE THREAD

**Issue by lcsig156** [abrignoni/ALEAPP#214]
Is this package needed to install ALEAPP?
keep getting this error:
ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from -r requirements.txt (line 12)) (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14 (from -r requirements.txt (line 12))

**Comment by abrignoni** [comment]
What python version are you using? Try 3.9. Stay away from 3.10 until
libraries are updated.

**Comment by lcsig156** [comment]
Sorry...when i check my version python3 --version it says 3.8.10,  I installed 3.9.1 and when I run python3.9 -V it gives me Python 3.9.10

**Comment by onateuth** [comment]
Hello, 
Same for me under Ubuntu, win10 and un VM. 
Don't know what to do

**Comment by abrignoni** [comment]
Check the solution in this thread:

https://github.com/abrignoni/iLEAPP/issues/266#issue-1116918948

**Comment by onateuth** [comment]
worked on Ubuntu
thanks
