### ISSUE TITLE
Future as artifacts

### ISSUE THREAD

**Issue by upintheairsheep** [abrignoni/ALEAPP#225]
I see how this tool could be used in being a historian in the future.

Add:

*Netflix artifacts
*Roblox 

And here are system related:
*ADB keys - could be used to identify if the system was modified
*Bluetooth logs - can solve a traffic accident
*Android Easter Egg data - on Nougat and Red Velvet Cake it is the cats you collect and their names. Red Velvet Cake also has data on the homekit widgets and snow cone only has if you unlocked the widget.

**Comment by upintheairsheep** [comment]
*tor bookmarks

**Comment by upintheairsheep** [comment]
- [File Manager+](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager&hl=en_US&gl=US)
- Gallery (Default app) cache
- Helium backups
- Dessert names

**Comment by upintheairsheep** [comment]
[Android API Levels to names.csv](https://github.com/abrignoni/ALEAPP/files/8148260/Android.API.Levels.to.names.csv)
These are dessert names as a companion to the api level.

**Comment by abrignoni** [comment]
Closing these request threads. They became long "parse every app ever invented without the requester providing any coding support or sample data to assist" threads. Totally useless.
