### ISSUE TITLE
Future projects requests

### ISSUE THREAD

**Issue by upintheairsheep** [abrignoni/ALEAPP#226]
- OCFDET (open cloud forensic data extractor tool), basically the open source data extractor for cloud data and downloads it, and to be phased with RLEAPP or another tool you’ll make
- MLEAPP - macOS data
- KLEAPP - KaiOS data
- MMMPLEAPP (Miscellaneous Mobile Phone LEAPP)
- CLEAPP - Chrome OS 
- iPodLEAPP - old iPods, non iOS
- LLEAPP - Linux, especially useful for hacking cases
- OFDET (open forensic data extraction tool): open source tool to extract data from mobile devices, desktop computers, mass media storage devices, video game consoles, internet of things devices, and more via all known methods. Reply for all known methods of extraction of data. Fun fact: this tool is also useful in digital preservation, a whole different field.
- IoTLEAPP - internet of things devices including Smart Televisions
- VGCLEAPP - video game consoles

**Comment by abrignoni** [comment]
Closing these request threads. They became long "parse every app ever invented without the requester providing any coding support or sample data to assist" threads. Totally useless.
