### ISSUE TITLE
Support these backup files & folders (checklist)

### ISSUE THREAD

**Issue by upintheairsheep** [abrignoni/ALEAPP#228]
*Android ADB Backup (.ab)
*Android Recovery Mode Backup (.backup)
*EXT4 image (.ext4)
*Samsung Smart Switch Backup Folder
*Huewi HiSuite/KoBackup backup folder
*Xaomi Backup folder
*Backup Your Mobile Backup Folder
*TWRP backup
*Clockworkmod backup
*Enhanced Android Backup (.abex) 
*Seedvault backup

android emulator disk images as well.

**Comment by abrignoni** [comment]
Closing these request threads. They became long "parse every app ever invented without the requester providing any coding support or sample data to assist" threads. Totally useless.
