### ISSUE TITLE
Problem Reading Android Triage data

### ISSUE THREAD

**Issue by dawidol** [abrignoni/ALEAPP#301]
Hi

I made an extraction with Android Triage, the output was around 80 Gb. I select the folder in ALEAPP but the final output html file does not have any information, any idea what could go wrong? Thanks a lot

**Comment by abrignoni** [comment]
There aren't any parser made for an Android Triage extraction. It only
supports full file system extractions.

**Comment by dawidol** [comment]
oh that is ti then, I read a post that claims android triage and aleapp are compatible. Thank you for your answer
