### ISSUE TITLE
onefile/noconsole no longer allowed PyInstaller 5.7.0

### ISSUE THREAD

**Issue by TroySchnack** [abrignoni/ALEAPP#306]
The two command lines for creating a standalone EXE are no longer allowed in the new version of Python 3.11.1 / PyInstaller 5.7.0

If running PyInstaller with just the .SPEC file, it fails with the following:

PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_plugin_loader required by hook for module C:\Users\xxxx\Desktop\Forensics\xLEAPP\ALEAPP-master 2022-12-28\ALEAPP-master\hook-plugin_loader.py. Please check whether module __PyInstaller_hooks_0_plugin_loader actually exists and whether the hook is compatible with your version of C:\Users\xxxx\Desktop\Forensics\xLEAPP\ALEAPP-master 2022-12-28\ALEAPP-master\hook-plugin_loader.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

**Comment by abrignoni** [comment]
Leave the arguments out. The binary should work. Execute pyinstaller from a fresh copy of the code.

**Comment by TroySchnack** [comment]
I just tried with the latest code. Same error as above.

command: **pyinstaller aleappGUI.spec**

PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_plugin_loader required by hook for module C:\Users\xxxx\Desktop\Forensics\xLEAPP\ALEAPP-master\hook-plugin_loader.py. Please check whether module __PyInstaller_hooks_0_plugin_loader actually exists and whether the hook is compatible with your version of C:\Users\xxxx\Desktop\Forensics\xLEAPP\ALEAPP-master\hook-plugin_loader.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.

**Comment by abrignoni** [comment]
Uninstall and reinstall pyinstaller and try again from fresh code.

I just made the binaries (will release tonight) and it worked. Also try
another box to see. Just in case if you can.

If it doesn't work let me know and I'll ask folks that know way more than
me about it.

**Comment by TroySchnack** [comment]
Update: Workaround

Creating the EXE works great under Python for Windows x64 v3.10.9 - does not work under v3.11.1

**Comment by abrignoni** [comment]
Fixed. Now works under v3.11.1.  When using pyinstaller do not use any arguments as mentioned previously,
