### ISSUE TITLE
Magic Bin for MacOS

### ISSUE THREAD

**Issue by fabian-nunes** [abrignoni/ALEAPP#337]
Hello I do not know if it is only a problem with my Mac, but in both my models (m1 and M1 Pro) I needed to replace the requirements from magic-bin to magic just like windows, only after that would the GUI work, I had other problems but where related to the incompatibilities in Homebrew. Is it possible a problem between ARM and x86 versions? Could somebody run magic-bin on a M1.

I had this error

ERROR: Could not find a version that satisfies the requirement python-magic-bin (from versions: none)
ERROR: No matching distribution found for python-magic-bin

That is why I had it changed in my pull request.

**Comment by abrignoni** [comment]
I have an Intel macbookPro. It has to be a difference between arm and x86
then. 🤔

We need to make a note in the read me. I don't know enough about pip to
know it there is something that would discriminate between chipsets when
deciding what package to use.

Thoughts?

**Comment by fabian-nunes** [comment]
A solution could be to add an extra check to the requirements txt such as:

```python
#Mac intel python magic-bin
python-magic-bin==0.4.14; platform_system == "Darwin" and platform_machine == "x86_64"
#Mac m1 python magic
python-magic==0.4.27; platform_system == "Darwin" and platform_machine == "arm64"
```
