### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by pshem** [abrignoni/ALEAPP#42]
Hi @abrignoni and @ydkhatri,

I was hoping to use some of the code in this repository in a personal project, but I noticed that the repository in general doesn't have a license. The following files already have licenses:
- `scripts/parse3.py` is licensed under the GPLv2
- `scripts/blackboxprotobuff.txt` is under the MIT License
- `scripts/MDB-Free_4.13.0/js/jquery.js` is under the MIT License
- `scripts/MDB-Free_4.13.0/css/mdb.css` is under the MIT License
- `scripts/MDB-Free_4.13.0/css/mdb.lite.css` is under the MIT License

But everything else is in a legal gray area. 

Thank you in advance!

**Comment by abrignoni** [comment]
Hi @pshem,
The full project is now under the MTI License.
