### ISSUE TITLE
Is six or soupsieve a requirement?

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/ALEAPP#46]
https://github.com/abrignoni/ALEAPP/blob/d1ba1f5dadb42d4da636594bfd564a8aa15636e6/requirements.txt#L5

I don't see it being used in code. Same for the `six` library

**Comment by abrignoni** [comment]
Most likely not. It guess it is a vestige from the old ileapp code that was
use as a basis for ALEAPP at the time.

**Comment by ydkhatri** [comment]
Removed them now.
