### ISSUE TITLE
ALEAPP mangles password in "Login Data" + does not decrypt

### ISSUE THREAD

**Issue by evandrix** [abrignoni/ALEAPP#49]
<img width="1552" alt="Screenshot 2020-05-14 at 02 42 15" src="https://user-images.githubusercontent.com/169669/81851847-b0a84800-958c-11ea-9a0a-4be3d31f38e2.png">

- mangled => so copy/paste doesn't work, how about printing the hex bytes after v10/11 instead of raw bytes?
- encrypted => so the following code i wrote decrypts:

```
#!/usr/bin/env python3 -B -u
#-*- coding: utf-8 -*-

import re
import sys

from Crypto.Cipher import AES
from Crypto.Protocol.KDF import PBKDF2
def decrypt(ciphertxt,key):
	if re.match(rb"^v1[01]",ciphertxt): ciphertxt = ciphertxt[3:]
	niter = 1
	salt = b"saltysalt"
	derived = PBKDF2(key,salt,0x10,niter)
	iv = b" "*0x10
	cipher = AES.new(derived,AES.MODE_CBC,IV=iv)
	plaintxt_pad = cipher.decrypt(ciphertxt)
	plaintxt = plaintxt_pad[:-ord(plaintxt_pad[len(plaintxt_pad)-1:])]
	return plaintxt

if __name__ == "__main__":
	# passwd = bytes.fromhex("7631306e673b542765b5f43672e7d62e19ca44") # badpasswird2
	# passwd = bytes.fromhex("763130590028096ca5e6a4f5642da17d9b71c4") # badpassword666
	key = b"peanuts"
	print(decrypt(passwd,key))
	# android://DUl-WH9DO3d0JccYjfiwzdFVMO8ky20_JUGK1-sFzpNgN0Th23rP-9FDMQiL7NCI2gpgrluif4_Co64j1AC9fQ==@com.zynga.chess.googleplay/ chess.master.chester / badpasswird2
	# https://login.live.com king.chester.802@gmail.com / badpassword666

```

**Comment by ydkhatri** [comment]
Thanks for pointing this out. I will implement this shortly.

**Comment by ydkhatri** [comment]
OK, now added to ALEAPP.

**Comment by abrignoni** [comment]
I dont see the Crypto.Cipher library in the repository. Getting module not found errors

**Comment by ydkhatri** [comment]
PyCryptodome fixes this, its been added to requirements.txt

**Comment by evandrix** [comment]
yeah, what @ydkhatri said, but just as additional info - `pycrypto` used to be the standard way to do cryptography in python, esp. 2.7.x, then it became outdated, now `pycryptodome` is the way forward, but just in case you don't want to pollute the namespace of `pycrypto`, i.e. you want `pycrypto` side-by-side with `pycryptodome`, then install `pycryptodomex` instead
