### ISSUE TITLE
3.2.3 GUI version not working

### ISSUE THREAD

**Issue by Rihe-hub** [abrignoni/ALEAPP#508]
Hello,

There is an issue with the GUI Windows version when parsing an extraction, screen remains empty.
<img width="678" alt="aleapp_3 2 3" src="https://github.com/user-attachments/assets/350a7b66-42fc-4482-90d0-6dd62cf2d313">

No problem with the Windows GUI version when building manually the GUI version from source code.

Thanks

**Comment by Rihe-hub** [comment]
I was able to reproduce the "empty screen" issue by modifying "console=True" to "console=False" in aleappGUI.spec file

When building GUI Windows version with "console=True", it's working fine (or at least log console is working)

**Comment by Johann-PLW** [comment]
This was fixed and an updated file has just been uploaded.
Thank you very much.

**Comment by Rihe-hub** [comment]
Many thanks, that was quick.

Could you share what we should change in spec file to build it without console or update the one available in public?

**Comment by Johann-PLW** [comment]
The aleappGUI.spec and ileappGUI.spec files pushed on the repo only included changes to populate the details tab of Windows file properties.
Console parameters changes were only made locally on my own computer.
But Tkinter needs `console=True` to be able to display logs in the GUI. I also added `hide_console='hide-early'` to hide the console but it seems working on Windows 10 but not with Windows 11.
So you can use the repo .spec files if you want to build the binaries yourself.

Thank you again for reporting the issue.
