### ISSUE TITLE
Wrong join in the Waze parser

### ISSUE THREAD

**Issue by koodekraker** [abrignoni/ALEAPP#519]
In the Waze parser, the table RECENTS and PLACES are join, but based on the wrong id.
There is a place_id in the RECENTS table, which should be used to join them together instead of the primary key of the RECENTS table itself.

Scripts/artifacts/waze.py:22

`join RECENTS on PLACES.id = RECENTS.id`

should be

`join RECENTS on PLACES.id = RECENTS.place_id`

**Comment by stark4n6** [comment]
Closing thanks to PR

**Comment by koodekraker** [comment]
Your're welcome, thanks for the awesome tool!
