### ISSUE TITLE
ALEAPP complete finished Close and Open No Report

### ISSUE THREAD

**Issue by jtchevy** [abrignoni/ALEAPP#535]
Hi all, I updated to latest version and ran on FFS of an Android.  Windows GUI, it will run and complete. I select Close and Open Report, it only goes back to ALEAPP.  I can see all the data in Exported Folder.  I ran the same extraction in an older version and it worked.
Thank you.
JLT

**Comment by jtchevy** [comment]
I have uninstalled reinstalled and same issue, no report opens, got back to aleapp to load file and output?
I got to the report folder all the data is there but no Report?
JLT

**Comment by Johann-PLW** [comment]
Hi @jtchevy,
We were not able to reproduce the bug you reported yesterday on Windows with both latest binary and source code.
I used an Android FFS Zip extraction and also a folder containing any matching file with all artifacts selected 
Could you provide more details about the source (zip, tar or folder) and output folder you used?

**Comment by jtchevy** [comment]
Zip I can share the log if you like!.

**Comment by jtchevy** [comment]
I had it output to the hard drive , it say it created a Report HTML , it
make export all data but no Report
JT

**Comment by jtchevy** [comment]
It was from Cellebrite rip Full File System, Samsung Galaxy SM-S146LV, device had no passcode.
v/r JT

**Comment by jtchevy** [comment]
it Report this 
Report location: E:\Output\ALEAPP_Reports_2024-12-15_Sunday_225331

but no Report was found only the data

**Comment by Johann-PLW** [comment]
Yes please. I am interested in having a look to the log file. You can provide the `Script Logs\Screen Output.html` file to the complete Script Logs folder
If you could also provide which version of Python you use.
Thank you very much.

**Comment by jtchevy** [comment]
Much appreciated if you all can assist me. 
JT

**Comment by jtchevy** [comment]
[log.txt](https://github.com/user-attachments/files/18160764/log.txt)
very much appreciated.
JT

**Comment by Johann-PLW** [comment]
I do not see any issue with log generation.
Can you confirm me that:
- When you click the `Open Report & Close` button, the ALEAPP GUI windows closes
- When you browse the `E:\Output\ALEAPP_Reports_2024-12-15_Sunday_225331` folder, you see at list the following folders: `_elements`, `Script Logs` and `temp`. In that case, do you find any index.html file?

**Comment by jtchevy** [comment]
yes it closes I will check for the follows for index files

**Comment by jtchevy** [comment]
yes sir! when I open the index.html it goes back to aleapp

**Comment by jtchevy** [comment]
When I click on the index.html it goes back to aleapp
See attached

**Comment by jtchevy** [comment]
No sure if you got my image of screen shot showing it opens back to aleapp menu
thank you JT

**Comment by jtchevy** [comment]
Will be trying on diff system, I can find anything that would prevent it from opening into report? So you know my background have been in forensic since mid 1988, old school.. thank you much.
JT stepping away to diff system

**Comment by Johann-PLW** [comment]
I didn't receive the screenshot.
But I suppose when you double-click on the index.html file, it opens the ALEAPP HTML report.
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/59add314-8486-413f-8d5f-b117c68f30db" />

I think Python is not able to open your default web browser to open the HTML file when you click on `Open Report & Close` button.

**Comment by jtchevy** [comment]
No Sir it open new ALEAPP file to load source and select output location.
JT

**Comment by jtchevy** [comment]
I will try a few things

**Comment by Johann-PLW** [comment]
Strange,
The HTML file is not supposed to open the ALEAPP Python script but the html report.

**Comment by jtchevy** [comment]
I meant "Hopped" over.. been a long two days.
JT

**Comment by jtchevy** [comment]
Please ping me if I can repay you.
JT

**Comment by Johann-PLW** [comment]
I'm glad I was able to help you and finally find a solution.

**Comment by jtchevy** [comment]
The problem was Browser, it won't open if default browser is Firebox l!
JT
