### ISSUE TITLE
Artifact_Report.py can't html escape int and NULL values

### ISSUE THREAD

**Issue by abrignoni** [abrignoni/ALEAPP#6]
Got this error:

<img width="1433" alt="Screen Shot 2020-03-02 at 12 42 55 AM" src="https://user-images.githubusercontent.com/28718987/75648669-c8735f80-5c1e-11ea-91cc-39ce12452b5a.png">

Was able to run the report function by using a CASE statement in the SQL query to clean up the null values and str(row[int]) at the data_list.append line. 

Any thoughts on how to normalize the output so no matter the field value fed to artifact_report.py (line 68) escapes them as strings? @ydkhatri

**Comment by abrignoni** [comment]
The other error was:
> AttributeError: 'int' object has no attribute 'replace'
NULL and int. Hope I made sense.

**Comment by ydkhatri** [comment]
This should be an easy fix. In the report function, we can just convert every input sent to a string using `str(..)` I will make the change.

**Comment by abrignoni** [comment]
Worked like a charm!
