### ISSUE TITLE
ADB hosts plugin

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/ALEAPP#74]
I'm not sure if this is correct. But this just reads the /system/etc/hosts file, which always seems to have the default content
```
127.0.0.1 localhost
::1       ip6-localhost
```
Has anyone seen anything else there?

On the other hand, there is an adb_keys file under /data/misc/adb, which has key and last connected system info like this:
```
<<KEY>> user@system
<<KEY>> user@system
```

**Comment by stark4n6** [comment]
It was generally created because of the Magnet CTF, which did have some different hosts configured

**Comment by ydkhatri** [comment]
> It was generally created because of the Magnet CTF, which did have some different hosts configured

Perhaps we should rename it to something else more appropriate, as simply connecting to phone via adb would not alter this file.

**Comment by stark4n6** [comment]
Sure go for it!

**Comment by ydkhatri** [comment]
Any suggestions? Since I haven't seen the altered file, I have no idea what it might have contained, or what it might have indicated. I'm guessing just IP addresses or host names hardcoded.

The plan would be to rename this, then parse hostnames from adb_keys file under a plugin with same name 'adb_hosts'.

**Comment by ydkhatri** [comment]
I renamed to Etc Hosts.

**Comment by stark4n6** [comment]
That works, thank you!
