### ISSUE TITLE
lgRCS throws exception

### ISSUE THREAD

**Issue by ydkhatri** [abrignoni/ALEAPP#97]
The regex for lgRCS `'*/mmssms.db*'`matches the other (default) mmssms database. Can we narrow this down by providing more of the path in the regex?

It is causing errors.
```
RCS Chats [lgRCS] artifact executing
Reading RCS Chats artifact had errors!
Error was no such table: message
Exception Traceback: Traceback (most recent call last):
  File "C:\Github\ALEAPP\scripts\ilap_artifacts.py", line 176, in process_artifact
    method(files_found, report_folder, seeker, wrap_text)
  File "C:\Github\ALEAPP\scripts\artifacts\lgRCS.py", line 43, in get_lgRCS
    cursor.execute('''
sqlite3.OperationalError: no such table: message
```

**Comment by abrignoni** [comment]
It's the same path, just an added table. Will handle the exception in case
table is not found. Thanks for pointing it out.

**Comment by abrignoni** [comment]
Code:
<img width="904" alt="Screen Shot 2021-01-10 at 3 47 14 PM" src="https://user-images.githubusercontent.com/28718987/104135077-b7759d80-535b-11eb-8237-db76cb766b90.png">

Output:
<img width="494" alt="Screen Shot 2021-01-10 at 3 48 23 PM" src="https://user-images.githubusercontent.com/28718987/104135085-c0666f00-535b-11eb-97a5-db6ecef587a5.png">

Thoughts @ydkhatri ?
The path/database for the LG branded RCS chats is the same as the sms mms database path in other Android installations.
Btw will be working on a RCS chats artifact for Pixel devices. They are kept in another database calle bugle_db.

**Comment by ydkhatri** [comment]
If it's the same db, we could possibly look at merging the code into the same module too. Can you share a sample with me? I'd like to take a look, and see how different it is from the normal.

**Comment by ydkhatri** [comment]
This isn't specific to LG, as it is the google Messages app that writes to the db. I am going to merge into the mmssms module.

**Comment by abrignoni** [comment]
Sent you the Google Pixel sample data. Google phone does not keep it in
that table. It uses a whole different database called bugle_db.

Thoughts?

**Comment by ydkhatri** [comment]
> Btw will be working on a RCS chats artifact for Pixel devices. They are kept in another database calle bugle_db.
bugle_db is where Hangout Chats also writes its data. It's all through google's messaging system, so I am not surprised.

**Comment by abrignoni** [comment]
Also if I am not mistaken Samsung phone keep RCS messages in another
location altogether from the two already mentioned. Working to get some
sample data on Samsung.

**Comment by ydkhatri** [comment]
It all depends on the App used by the end user. If they used Android's default Messaging app, it would end up in mmssms (and bugle).

**Comment by ydkhatri** [comment]
Most OEMs have their own app. Samsung's app is also called Messages, but it is a different one (than google's Messages).

**Comment by abrignoni** [comment]
Makes sense.

**Comment by ydkhatri** [comment]
> > Btw will be working on a RCS chats artifact for Pixel devices. They are kept in another database calle bugle_db.
> 
> bugle_db is where Hangout Chats also writes its data. It's all through google's messaging system, so I am not surprised.

Oops, thats **babel.db** for Hangouts! 
**bugle_db** also stores mmssms on Androids. I think eventually mmssms.db may be abandoned? On my images, I see sms and mms in both.

**Comment by abrignoni** [comment]
Notice the URI field in the bugle_db database. If you go to the link you
can see the shared files with no authentication required. 😬

If the picture is deleted the uri field is deleted too but the picture
remains online. Great to look for in a journaling file if the data is
deleted before one gets to it.

**Comment by ydkhatri** [comment]
I fixed the exception. FYI, in `ilapfuncs.py` there is a does_table_exist() 
https://github.com/abrignoni/ALEAPP/blob/b1b0e7f36dafe7b21862b72c30a29b8c827fd4ff/scripts/ilapfuncs.py#L95
and
 https://github.com/abrignoni/ALEAPP/blob/b1b0e7f36dafe7b21862b72c30a29b8c827fd4ff/scripts/ilapfuncs.py#L78 for these situations.
